image: php:8.0-apache

stages:
  - setup
  - start

variables:
  MYSQL_ROOT_PASSWORD: SIKessEm|DocMan
  MYSQL_HOST: mysql
  MYSQL_USER: sikessem
  MYSQL_PASSWORD: sikessem/docman:0.1.0-a
  MYSQL_DATABASE: docman

services:
  - mysql:8.0

site:
  stage: setup
  cache:
    paths:
      - pkg/
      - node_modules
  before_script:
    - apt-get update -yqq
    - apt-get upgrade -yqq
    - apt-get install -yqq git vim

  after_script:
    - vim --version
    - git --version
  script:
    - apt-get install -yqq libpq-dev libcurl4-gnutls-dev libicu-dev libvpx-dev libjpeg-dev libpng-dev libxpm-dev zlib1g-dev libfreetype6-dev libxml2-dev libexpat1-dev libbz2-dev libgmp3-dev libldap2-dev unixodbc-dev libsqlite3-dev libaspell-dev libsnmp-dev libpcre3-dev libtidy-dev libonig-dev libzip-dev
    - docker-php-ext-install mbstring pdo_mysql curl intl gd xml zip bz2 opcache

base:
  stage: setup
  image: mysql:8.0
  script:
    - echo "SELECT 'OK';" | mysql --user="$MYSQL_USER" --password="$MYSQL_PASSWORD" --host="$MYSQL_HOST" "$MYSQL_DATABASE"

client:
  stage: start
  image: node:16
  script:
    - yarn install
    - yarn start

server:
  stage: start
  image: composer:2.1
  script:
    - composer install
    - php cli/run