#!/usr/bin/env php
<?php

use SIKessEm\DocMan\{
  function it
};

require_once dirname(__DIR__) . '/pkg/autoload.php';

$it = it();

$input = $it->getInput();
$output = $it->getOutput();

$output->write('Your name ? : ');
$name = $input->read(1024);
$output->write("Welcome $name" . PHP_EOL);